/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as LoginOauthImport } from './routes/login/oauth'
import { Route as AuthUsersImport } from './routes/_auth/users'
import { Route as AuthRequestImport } from './routes/_auth/request'
import { Route as AuthRequestsIndexImport } from './routes/_auth/requests/index'
import { Route as AuthRequestsRequestIdImport } from './routes/_auth/requests/$requestId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const LoginOauthRoute = LoginOauthImport.update({
  path: '/login/oauth',
  getParentRoute: () => rootRoute,
} as any)

const AuthUsersRoute = AuthUsersImport.update({
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRequestRoute = AuthRequestImport.update({
  path: '/request',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRequestsIndexRoute = AuthRequestsIndexImport.update({
  path: '/requests/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRequestsRequestIdRoute = AuthRequestsRequestIdImport.update({
  path: '/requests/$requestId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/request': {
      preLoaderRoute: typeof AuthRequestImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users': {
      preLoaderRoute: typeof AuthUsersImport
      parentRoute: typeof AuthImport
    }
    '/login/oauth': {
      preLoaderRoute: typeof LoginOauthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/requests/$requestId': {
      preLoaderRoute: typeof AuthRequestsRequestIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/requests/': {
      preLoaderRoute: typeof AuthRequestsIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthRequestRoute,
    AuthUsersRoute,
    AuthIndexRoute,
    AuthRequestsRequestIdRoute,
    AuthRequestsIndexRoute,
  ]),
  LoginOauthRoute,
  LoginIndexRoute,
])

/* prettier-ignore-end */
