spring:
  application:
    name: KhNURE-timetable-synchronizer
    base-url: '/api/v1'

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/timetable}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
jwt:
  signature-secret: ${JWT_SIGNATURE_SECRET:mySecret}
schedule-api-url: 'https://api.mindenit.tech'

google:
  clientId: ${OAUTH2_GOOGLE_CLIENT-ID}
  clientSecret: ${OAUTH2_GOOGLE_CLIENT-SECRET}
  application:
    name: '[Desktop] KhNURE Timetable Synchronizer'