spring:
  application:
    name: KhNURE-timetable-synchronizer
    base-url: '/api/v1'

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/timetable}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}


schedule-api-url: 'https://api.mindenit.tech'
